# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build and package a development IPA"
  lane :dev do
    match(type: "development")
    gym(export_method: "development", scheme: "musicplayce", export_options: "./musicplayce/Debug.plist")
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    match(type: "development")
    match(type: "appstore")
    gym(scheme: "musicplayce", export_options: "./musicplayce/Release.plist")
    upload_to_testflight
  end

  desc "Push a new release build to the App Store"
  lane :release do
    build_app(scheme: "musicplayce")
    upload_to_app_store(skip_metadata: true, skip_screenshots: true)
  end
end
